"""Rebuild the vendored spacing table. Never downloads data."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'data/unicode/east-asian-spacing-utr59-r1.txt'
TARGET = ROOT / 'scripts/unicode_spacing_data.py'

def render():
    source = SOURCE.read_bytes()
    manifest = json.loads((ROOT / 'data/unicode/manifest.json').read_text(encoding='utf-8'))
    digest = hashlib.sha256(source).hexdigest()
    if digest != manifest['files'][SOURCE.relative_to(ROOT).as_posix()]:
        raise ValueError('Spacing source digest mismatch')
    text = source.decode('utf-8')
    if '# @missing: 0000..10FFFF; O' not in text:
        raise ValueError('Unexpected spacing default')
    ranges = []
    for line in text.splitlines():
        content = line.split('#', 1)[0].strip()
        if not content:
            continue
        m = re.fullmatch(r'([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([WNOC])', content)
        if not m:
            raise ValueError('Invalid spacing range: ' + content)
        lo, hi = int(m[1], 16), int(m[2] or m[1], 16)
        if not 0 <= lo <= hi <= 0x10FFFF:
            raise ValueError('Range outside Unicode')
        ranges.append((lo, hi, m[3]))
    ranges.sort()
    if any(a[1] >= b[0] for a, b in zip(ranges, ranges[1:])):
        raise ValueError('Overlapping spacing ranges')
    lines = ['# Generated by tools/generate_spacing_data.py; do not edit.',
             'SOURCE_SHA256 = ' + repr(digest), "DEFAULT = 'O'", 'RANGES = (']
    lines += [f'    (0x{lo:X}, 0x{hi:X}, {value!r}),' for lo, hi, value in ranges]
    return '\n'.join(lines + [')', ''])


def render_categories():
    source = ROOT / 'data/unicode/DerivedGeneralCategory-16.0.0.txt'
    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    manifest = json.loads((ROOT / 'data/unicode/manifest.json').read_text(encoding='utf-8'))
    if digest != manifest['files'][source.relative_to(ROOT).as_posix()]:
        raise ValueError('General category source digest mismatch')
    rows = []
    for line in raw.decode('utf-8').splitlines():
        text = line.split('#', 1)[0].strip()
        if not text:
            continue
        m = re.fullmatch(r'([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Z][a-z])', text)
        if not m:
            raise ValueError('Invalid category record')
        rows.append((int(m[1], 16), int(m[2] or m[1], 16), m[3]))
    rows.sort()
    if rows[0][0] != 0 or rows[-1][1] != 0x10FFFF or any(a[1] + 1 != b[0] for a, b in zip(rows, rows[1:])):
        raise ValueError('Category data must cover Unicode exactly once')
    lines = ['# Generated Unicode16.0 categories; never use host unicodedata.',
             'SOURCE_SHA256 = ' + repr(digest), 'CATEGORY_RANGES = (']
    lines += [f'    (0x{lo:X}, 0x{hi:X}, {value!r}),' for lo, hi, value in rows]
    return '\n'.join(lines + [')', ''])

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    categories = render_categories().encode('utf-8')
    category_target = ROOT / 'scripts/unicode_category_data.py'
    if args.check:
        if not category_target.exists() or category_target.read_bytes() != categories:
            print('Generated category data drift', file=sys.stderr)
            return 1
    else:
        category_target.write_bytes(categories)
    expected = render().encode('utf-8')
    if args.check:
        if not TARGET.exists() or TARGET.read_bytes() != expected:
            print('Generated spacing data drift', file=sys.stderr)
            return 1
    else:
        TARGET.write_bytes(expected)
    print('Spacing data OK')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
